spring:
    application:
        name: user-service
    config:
        import: "optional:configserver:http://localhost:8088"
    datasource:
        url: jdbc:h2:mem:glenn
    h2:
        console:
            enabled: true
    jpa:
        defer-datasource-initialization: true
        show-sql: true

server:
    port: 7070
    error:
        include-message: always

