server:
    error:
        include-message: always

spring:
    datasource:
        url: jdbc:h2:mem:glenn
    h2:
        console:
            enabled: true
    jpa:
        defer-datasource-initialization: true
        show-sql: true

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka