version: '3'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  apiGateway:
    build:
      context: "./api-gateway"
    ports:
      - 8060:8060
    depends_on:
      - zipkin
  