eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
server:
    error:
        include-message: always
    port: 6060
spring:
    application:
        name: order-service
    datasource:
        url: jdbc:h2:mem:glenn
    h2:
        console:
            enabled: true
    jpa:
        defer-datasource-initialization: true
        show-sql: true